#!/usr/bin/env sh

SHELL=/bin/sh

# source ~/.config/yabai/yabai-methods.sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --add app=".*" sub-layer=below
yabai -m rule --add app="^System Preferences$" sticky=on manage=off 
yabai -m rule --add app='^Preferences$' manage=off
# yabai -m rule --add app='^Godot$' manage=off
yabai -m rule --add title='.*\(DEBUG\)$' manage=off # sub-layer=above
yabai -m rule --add app="^Activity Monitor$" sticky=on sub-layer=above manage=off
# yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Spotify$" scratchpad='spotify' grid=11:11:1:1:9:9
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Transmission$" manage=off
yabai -m rule --add app='^VLC media player$' manage=off
yabai -m rule --add app='^Microsoft Teams$' manage=off scratchpad='teams' grid=11:11:1:1:9:9
# yabai -m rule --add app='^Microsoft Teams \(work or school\)$' manage=off
# yabai -m rule --add app='^Microsoft Teams \(work or school\)$' scratchpad='teams' grid=110:11:1:1:9:9
yabai -m rule --add app='^Microsoft Outlook$' manage=off
yabai -m rule --add app="^Calculator$" sticky=on sub-layer=above manage=off
yabai -m rule --add app='^qemu-system-aarch64$' manage=on # sub-layer=above

yabai -m rule --add app='^StartClient$' manage=off
yabai -m rule --add app='^LÖVE$' manage=off
yabai -m rule --add app='^love$' manage=off
yabai -m rule --add app='^Steam$' manage=off
yabai -m rule --add app='^Ueli$' manage=off

yabai -m rule --add app='^iTerm2$'
yabai -m rule --add app='^Übersicht$'

yabai -m rule --add app="^Finder$" manage=off sub-layer=below
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^zathura$" manage=on
yabai -m rule --add app="^Books$" manage=on
yabai -m rule --add app="^alacritty$" manage=on
yabai -m rule --add app="^bevy-prac$" manage=off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  02
yabai -m config bottom_padding				       02
yabai -m config left_padding                 02
yabai -m config right_padding                02
yabai -m config window_gap                   02

# spacing for simple-bar
yabai -m config external_bar all:28:0:0:0

yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label misc
yabai -m space 4 --label music

# focus window after active space changes
# yabai -m signal --add event=space_changed action="focus_window"

# focus window after active display changes
# yabai -m signal --add event=display_changed action="focus_window"

# sketchybar events (.yabairc)
#yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
#yabai -m signal -add event=window_minimized action="sketchybar -m --trigger window_focus &> /dev/null"
#yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

echo "yabai configuration loaded.."

# skhd -c $HOME/.config/skhd/skhdrc
