set-option -g default-shell /bin/zsh
set-option -sa terminal-overrides ",alacritty:RGB"
set-option -sg escape-time 10
set-option -g focus-events on
set -g visual-activity off
set -g visual-bell off
set -g mouse on

# Change prefix to Ctrl - b which is mapped to alt - e in skhd
set-option -g prefix C-b
bind-key C-b send-prefix

setw -g mode-keys vi

# Status bar
set -g status-style bg="#1E1E2E",fg=white
set -g status-right ''

setw -g window-status-current-style fg=colour2,bg="#45475A"
setw -g window-status-style fg=white,bg="#1E1E2E"

setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '
setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour255]#W#[fg=colour249]#F '

# Popup styles
set -g popup-style bg='#1e1e2e'
set -g popup-border-lines rounded
set -g popup-border-style fg=black

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind r split-window -h -c "#{pane_current_path}" \; resize-pane -R 40

# Open panes
bind l split-window -h -c "#{pane_current_path}"  
bind j split-window -v -c "#{pane_current_path}"  
bind h split-window -h -b -c "#{pane_current_path}"   
bind k split-window -v -b -c "#{pane_current_path}"   

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'pschmitt/tmux-ssh-split'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# tmux ssh
set -g @ssh-split-keep-cwd "true"
set -g @ssh-split-keep-remote-cwd "true"
set -g @ssh-split-w-key "C"

# Disable bindings
bind -n C-g
bind -n C-f

# bind -n C-f display-popup -E -w 90% -h 90% "lazydocker"
bind C-f display-popup -E -w 90% -h 90% "tmux new-session -A -s lazydocker 'lazydocker'"

run '~/.config/tmux/plugins/tpm/tpm'
