# set -g default-terminal "alacritty"
set-option -g default-shell /bin/zsh
set-option -sa terminal-overrides ",alacritty:RGB"
# set-option -sa terminal-overrides ",xterm*:Tc"
set -g status-bg "#1E1E2E"
set -g status-fg white
set -Fg 'status-format[1]' '#{status-format[0]}'
set-option -g status-style bg=default
set-option -sg escape-time 10
set-option -g focus-events on

set -g visual-activity off
set -g visual-bell off

setw -g mouse on

# Change prefix to Ctrl - b which is mapped to alt - e in skhd
set-option -g prefix C-b
bind-key C-b send-prefix

setw -g mode-keys vi
# bind-key M-h run-shell "if [ $(tmux display-message -p '#{pane_at_left}') -ne 1 ]; then tmux select-pane -L; else yabai -m window --focus west || true; fi"
# bind-key M-l run-shell "if [ $(tmux display-message -p '#{pane_at_right}') -ne 1 ]; then tmux select-pane -R; else yabai -m window --focus east || true; fi"
# bind-key M-j run-shell "if [ $(tmux display-message -p '#{pane_at_bottom}') -ne 1 ]; then tmux select-pane -D; else yabai -m window --focus north || true; fi"
# bind-key M-k run-shell "if [ $(tmux display-message -p '#{pane_at_top}') -ne 1 ]; then tmux select-pane -U; else yabai -m window --focus south || true; fi"

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind r split-window -h -c "#{pane_current_path}" \; resize-pane -R 40

bind l split-window -h -c "#{pane_current_path}"  
bind j split-window -v -c "#{pane_current_path}"  
bind h split-window -h -b -c "#{pane_current_path}"   
bind k split-window -v -b -c "#{pane_current_path}"   

# bind j select-pane -D
# bind l select-pane -R

set -g status-right ''

setw -g window-status-current-style fg=colour1 
setw -g window-status-current-style bg="#45475A"
setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour255]#W#[fg=colour249]#F '

setw -g window-status-style fg=colour1 
setw -g window-status-style bg="#1E1E2E"
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'pschmitt/tmux-ssh-split'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# tmux ssh
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-w-key "C"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
# bind -n C-g display-popup -E -w 90% -h 90% "lazydocker"
bind -n C-g
bind -n C-f
bind C-f display-popup -E -w 90% -h 90% "tmux new-session -A -s lazydocker 'lazydocker'"

set-option -g popup-style bg='#313244' # can't seem to add popup bg in .tmux.conf
set-option -g popup-border-lines rounded # can't seem to add popup bg in .tmux.conf

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
